export function renderSiteRegistryPage(): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Narada Site Registry</title>
  <style>
    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, sans-serif; color: #17212b; background: #f4f6f8; }
    * { box-sizing: border-box; } body { margin: 0; min-width: 320px; } button, input, select, textarea { font: inherit; }
    .bar { min-height: 56px; display: flex; align-items: center; gap: 16px; padding: 10px 20px; background: #17212b; color: #f6fbff; }
    .bar h1 { margin: 0; font-size: 17px; font-weight: 650; } .bar p { margin: 0; color: #b9c8d4; font-size: 13px; } .spacer { flex: 1; }
    button { border: 1px solid #8ea2b2; border-radius: 5px; background: #f6fbff; color: #17212b; padding: 7px 10px; cursor: pointer; } button:hover { background: #dcecf5; } button:disabled { cursor: not-allowed; opacity: .55; }
    main { display: grid; grid-template-columns: minmax(360px, 1fr) minmax(360px, 1fr); gap: 16px; padding: 16px; max-width: 1600px; margin: 0 auto; }
    section { min-width: 0; background: #fff; border: 1px solid #d7dfe5; border-radius: 6px; } .wide { grid-column: 1 / -1; }
    .section-head { display: flex; align-items: center; gap: 10px; min-height: 48px; padding: 10px 14px; border-bottom: 1px solid #d7dfe5; } .section-head h2 { margin: 0; font-size: 15px; font-weight: 650; } .count { color: #5c6c78; font-size: 13px; }
    .content { padding: 14px; } table { width: 100%; border-collapse: collapse; table-layout: fixed; font-size: 13px; } th, td { padding: 9px 8px; text-align: left; border-bottom: 1px solid #e8edf0; vertical-align: top; overflow-wrap: anywhere; } th { color: #53636f; font-size: 11px; font-weight: 650; text-transform: uppercase; letter-spacing: .04em; } tbody tr { cursor: pointer; } tbody tr:hover, tbody tr[aria-selected="true"] { background: #eaf4f8; }
    .state { display: inline-flex; max-width: 100%; padding: 2px 6px; border-radius: 4px; font-size: 12px; line-height: 1.3; } .active, .present { color: #155d38; background: #dff3e8; } .retired, .missing, .conflicted { color: #842029; background: #f9e1e3; } .stale, .unverified { color: #765600; background: #fff1c5; }
    dl { margin: 0; display: grid; grid-template-columns: 150px minmax(0, 1fr); gap: 9px 14px; font-size: 13px; } dt { color: #586873; } dd { margin: 0; overflow-wrap: anywhere; } .list { margin: 0; padding-left: 18px; } .list li { margin: 0 0 6px; }
    .empty, .error { color: #5c6c78; font-size: 14px; padding: 22px 6px; } .error { color: #8a2731; } pre { margin: 0; padding: 12px; max-height: 300px; overflow: auto; background: #f5f8fa; border: 1px solid #d7dfe5; border-radius: 5px; font: 12px/1.45 ui-monospace, SFMono-Regular, Consolas, monospace; white-space: pre-wrap; overflow-wrap: anywhere; }
    .form-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px 14px; } .field { display: grid; gap: 5px; font-size: 13px; color: #44545f; } .field input, .field select, .field textarea { width: 100%; min-height: 34px; border: 1px solid #b8c5ce; border-radius: 4px; padding: 6px 8px; color: #17212b; background: #fff; } .field textarea { min-height: 72px; resize: vertical; } .span-2 { grid-column: span 2; } .span-3 { grid-column: span 3; } .actions { display: flex; align-items: center; gap: 10px; margin-top: 14px; flex-wrap: wrap; } .confirmation { display: flex; align-items: center; gap: 7px; font-size: 13px; color: #44545f; }
    @media (max-width: 900px) { main { grid-template-columns: 1fr; padding: 10px; } .wide { grid-column: auto; } .bar { align-items: flex-start; flex-wrap: wrap; } .spacer { display: none; } .form-grid { grid-template-columns: 1fr; } .span-2, .span-3 { grid-column: auto; } }
  </style>
</head>
<body>
  <header class="bar"><div><h1>Site Registry</h1><p>Canonical user-site inventory</p></div><div class="spacer"></div><button id="refresh" type="button">Refresh</button><button id="discover" type="button">Preview Discovery</button></header>
  <main>
    <section><div class="section-head"><h2>Sites</h2><span id="count" class="count"></span></div><div class="content" id="site-list"><p class="empty">Loading registry...</p></div></section>
    <section><div class="section-head"><h2>Record Detail</h2></div><div class="content" id="detail"><p class="empty">Select a Site to inspect its canonical record.</p></div></section>
    <section class="wide"><div class="section-head"><h2>Registry Change</h2><span class="count">Preview before apply</span></div><div class="content"><form id="mutation-form"><div class="form-grid">
      <label class="field"><span>Operation</span><select id="operation"><option value="add">Add</option><option value="edit">Edit</option><option value="retire">Retire</option><option value="restore">Restore</option><option value="purge">Purge</option></select></label>
      <label class="field"><span>Canonical Site ID</span><input id="site-id" autocomplete="off"></label><label class="field"><span>Reference</span><input id="reference" autocomplete="off"></label>
      <label class="field span-2"><span>Root</span><input id="root" autocomplete="off"></label><label class="field"><span>Reason</span><input id="reason" autocomplete="off"></label>
      <label class="field"><span>Variant</span><input id="variant" placeholder="native" autocomplete="off"></label><label class="field"><span>Substrate</span><input id="substrate" autocomplete="off"></label><label class="field"><span>Source</span><input id="source" placeholder="manual" autocomplete="off"></label>
      <label class="field span-2"><span>Control endpoint</span><input id="control-endpoint" autocomplete="off"></label><label class="field"><span>Source reference</span><input id="source-ref" autocomplete="off"></label>
      <label class="field span-3"><span>Aliases</span><input id="aliases" placeholder="comma-separated" autocomplete="off"></label><label class="field span-3"><span>Aim JSON</span><textarea id="aim-json" spellcheck="false"></textarea></label>
    </div><div class="actions"><label class="confirmation"><input id="re-admit" type="checkbox"> Re-admit retired record</label><button id="plan" type="submit">Preview Change</button><label class="confirmation"><input id="confirm-apply" type="checkbox" disabled> Confirm apply</label><button id="apply" type="button" disabled>Apply Planned Change</button></div></form><div id="mutation-output" style="margin-top:14px"><p class="empty">No change preview requested.</p></div></div></section>
    <section class="wide"><div class="section-head"><h2>Discovery Preview</h2><span class="count">Read-only dry run</span></div><div class="content" id="discovery-output"><p class="empty">No preview requested.</p></div></section>
  </main>
  <script>
    const listEl = document.getElementById('site-list'); const detailEl = document.getElementById('detail'); const countEl = document.getElementById('count'); const discoveryEl = document.getElementById('discovery-output'); const mutationOutput = document.getElementById('mutation-output'); const applyButton = document.getElementById('apply'); const confirmApply = document.getElementById('confirm-apply');
    let selectedReference = null; let plannedMutation = null;
    const value = (id) => document.getElementById(id).value.trim(); const checked = (id) => document.getElementById(id).checked;
    function stateClass(value) { return String(value || '').replace(/[^a-z-]/g, ''); } function state(value) { const span = document.createElement('span'); span.className = 'state ' + stateClass(value); span.textContent = value || 'unknown'; return span; } function text(value) { return value == null || value === '' ? '—' : String(value); } function clear(node) { while (node.firstChild) node.removeChild(node.firstChild); } function showError(node, message) { clear(node); const p = document.createElement('p'); p.className = 'error'; p.textContent = message; node.appendChild(p); }
    async function request(path, options) { const response = await fetch(path, options); const body = await response.json(); if (!response.ok) throw new Error(body.error || body.detail || (body.refusals || []).join(', ') || 'Request failed'); return body; }
    function renderList(payload) { clear(listEl); const sites = Array.isArray(payload.sites) ? payload.sites : []; countEl.textContent = sites.length + (sites.length === 1 ? ' Site' : ' Sites'); if (!sites.length) { const p = document.createElement('p'); p.className = 'empty'; p.textContent = 'No Sites are registered.'; listEl.appendChild(p); return; } const table = document.createElement('table'); table.innerHTML = '<thead><tr><th>Site</th><th>Lifecycle</th><th>Observation</th><th>Provenance</th><th>Revision</th></tr></thead>'; const body = document.createElement('tbody'); for (const site of sites) { const row = document.createElement('tr'); row.tabIndex = 0; row.setAttribute('aria-selected', String(site.site_id === selectedReference)); const cells = [site.site_id, state(site.lifecycle_status), state(site.observation_status), (site.sources || []).map((item) => item.kind).join(', ') || '—', site.revision]; for (const item of cells) { const td = document.createElement('td'); if (item instanceof Node) td.appendChild(item); else td.textContent = text(item); row.appendChild(td); } row.addEventListener('click', () => selectSite(site.site_id)); row.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); selectSite(site.site_id); } }); body.appendChild(row); } table.appendChild(body); listEl.appendChild(table); }
    function renderDetail(payload) { clear(detailEl); if (payload.status !== 'success' || !payload.site) { showError(detailEl, (payload.refusals || ['Site record unavailable']).join(', ')); return; } const site = payload.site; const dl = document.createElement('dl'); const rows = [['Canonical ID', site.site_id], ['Root', site.site_root], ['Control endpoint', site.control_endpoint], ['Variant / substrate', [site.variant, site.substrate].filter(Boolean).join(' / ')], ['Lifecycle', site.lifecycle_status], ['Observation', site.observation_status], ['Revision', site.revision], ['Created', site.created_at], ['Updated', site.updated_at], ['Last seen', site.last_seen_at], ['Retired', site.retired_at], ['Retire reason', site.retire_reason]]; for (const [label, item] of rows) { const dt = document.createElement('dt'); dt.textContent = label; const dd = document.createElement('dd'); if (label === 'Lifecycle' || label === 'Observation') dd.appendChild(state(item)); else dd.textContent = text(item); dl.append(dt, dd); } const sources = document.createElement('dd'); const sourceList = document.createElement('ul'); sourceList.className = 'list'; for (const source of site.sources || []) { const li = document.createElement('li'); li.textContent = [source.kind, source.ref, source.observed_at].filter(Boolean).join(' · '); sourceList.appendChild(li); } sources.appendChild(sourceList); const sourcesLabel = document.createElement('dt'); sourcesLabel.textContent = 'Provenance'; dl.append(sourcesLabel, sources); const aliases = document.createElement('dd'); aliases.textContent = (site.aliases || []).map((alias) => alias.value + ' (' + alias.source + ')').join(', ') || '—'; const aliasesLabel = document.createElement('dt'); aliasesLabel.textContent = 'Aliases'; dl.append(aliasesLabel, aliases); const next = document.createElement('dd'); next.textContent = (payload.next_actions || []).join(', ') || '—'; const nextLabel = document.createElement('dt'); nextLabel.textContent = 'Next actions'; dl.append(nextLabel, next); const conflicts = document.createElement('dd'); conflicts.textContent = (payload.conflicts || []).map(String).join(', ') || 'None'; const conflictsLabel = document.createElement('dt'); conflictsLabel.textContent = 'Conflicts'; dl.append(conflictsLabel, conflicts); detailEl.appendChild(dl); }
    async function loadList() { try { const payload = await request('/console/registry/api/sites', { headers: { Accept: 'application/json' } }); renderList(payload); if (selectedReference) await selectSite(selectedReference, false); } catch (error) { showError(listEl, error.message); } } async function selectSite(reference, redraw = true) { selectedReference = reference; document.getElementById('reference').value = reference; try { const payload = await request('/console/registry/api/sites/' + encodeURIComponent(reference), { headers: { Accept: 'application/json' } }); renderDetail(payload); if (redraw) await loadList(); } catch (error) { showError(detailEl, error.message); } }
    function mutationInput() { const aliases = value('aliases') ? value('aliases').split(',').map((item) => item.trim()).filter(Boolean) : undefined; return { operation: value('operation'), site_id: value('site-id') || undefined, reference: value('reference') || undefined, root: value('root') || undefined, variant: value('variant') || undefined, substrate: value('substrate') || undefined, aim_json: value('aim-json') || undefined, control_endpoint: value('control-endpoint') || undefined, aliases, source: value('source') || undefined, source_ref: value('source-ref') || undefined, reason: value('reason') || undefined, re_admit: checked('re-admit') || undefined }; }
    function showJson(node, payload) { clear(node); const pre = document.createElement('pre'); pre.textContent = JSON.stringify(payload, null, 2); node.appendChild(pre); }
    function previewRevision(payload) { const before = payload.before; return Number.isInteger(before?.revision) ? before.revision : undefined; }
    async function previewMutation(event) { event.preventDefault(); plannedMutation = null; applyButton.disabled = true; confirmApply.checked = false; confirmApply.disabled = true; try { const input = mutationInput(); const payload = await request('/console/registry/api/operations/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }); plannedMutation = { input, expected_revision: previewRevision(payload), confirm_site_id: payload.confirmation_required || undefined }; showJson(mutationOutput, payload); confirmApply.disabled = false; applyButton.disabled = !confirmApply.checked; } catch (error) { showError(mutationOutput, error.message); } }
    async function applyMutation() { if (!plannedMutation || !confirmApply.checked) return; try { const input = { ...plannedMutation.input, expected_revision: plannedMutation.expected_revision, confirm_site_id: plannedMutation.confirm_site_id, confirm_apply: true }; const payload = await request('/console/registry/api/operations/apply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }); showJson(mutationOutput, payload); plannedMutation = null; confirmApply.checked = false; confirmApply.disabled = true; applyButton.disabled = true; await loadList(); } catch (error) { showError(mutationOutput, error.message); } }
    async function previewDiscovery() { clear(discoveryEl); try { const payload = await request('/console/registry/api/discover-plan', { headers: { Accept: 'application/json' } }); showJson(discoveryEl, payload); } catch (error) { showError(discoveryEl, error.message); } }
    document.getElementById('refresh').addEventListener('click', loadList); document.getElementById('discover').addEventListener('click', previewDiscovery); document.getElementById('mutation-form').addEventListener('submit', previewMutation); confirmApply.addEventListener('change', () => { applyButton.disabled = !confirmApply.checked || !plannedMutation; }); applyButton.addEventListener('click', applyMutation); loadList();
  </script>
</body>
</html>`;
}