export const NARS_COMMAND_METHOD: 'session.command.execute';
export const LEGACY_CARRIER_COMMAND_METHOD: 'carrier.command.execute';
export const NARS_CLIENT_PROJECTION_VERBOSITY_LEVELS: readonly ['conversation', 'operations', 'diagnostics', 'raw'];
export type NarsClientProjectionVerbosity = typeof NARS_CLIENT_PROJECTION_VERBOSITY_LEVELS[number];
export type NarsClientProjectionClass = 'conversation' | 'operations' | 'diagnostics' | 'raw';
export const NARS_CLIENT_PROJECTION_DEFAULT_VERBOSITY: NarsClientProjectionVerbosity;
export const NARS_CLIENT_PROJECTION_VERBOSITY_RANK: Readonly<Record<NarsClientProjectionVerbosity, number>>;
export const AGENT_WEB_UI_NARS_METHOD_LIST: readonly string[];
export const AGENT_WEB_UI_SESSION_COMMANDS: readonly string[];
export const AGENT_WEB_UI_CARRIER_COMMANDS: readonly string[];
export type AgentWebUiCommandKind = 'local_ui' | 'nars_protocol' | 'nars_session_command' | 'raw_protocol_frame';
export type AgentWebUiCommandGroup = 'conversation' | 'session' | 'diagnostics' | 'settings' | 'local' | 'advanced';
export interface AgentWebUiCommand {
  id: string;
  slash: `/${string}`;
  aliases: readonly `/${string}`[];
  kind: AgentWebUiCommandKind;
  group: AgentWebUiCommandGroup;
  title: string;
  description: string;
  keywords: readonly string[];
  usage: string;
  palette: Readonly<{ visible: boolean; rank: number; danger: boolean }>;
  buildAction(input: object, context?: object): object;
}
export const AGENT_WEB_UI_COMMANDS: readonly AgentWebUiCommand[];
export const AGENT_WEB_UI_COMMAND_GROUP_LABELS: Readonly<Record<AgentWebUiCommandGroup, string>>;
export const AGENT_WEB_UI_HELP_LINES: readonly string[];
export const NARS_CLIENT_EVENT_TONES: Readonly<Record<string, string>>;
export const NARS_CLIENT_EVENT_LABELS: Readonly<Record<string, string>>;
export const AGENT_WEB_UI_NARS_METHODS: ReadonlySet<string>;
export const NARS_CLIENT_PROJECTION_REGISTRY: unknown;

export interface NarsClientProjection {
  kind: string;
  class?: NarsClientProjectionClass;
  label: string;
  tone: string;
  summary: unknown;
  event: unknown;
  renderKey?: string;
}

export function isAgentWebUiNarsMethod(method: unknown): boolean;
export function buildNarsArtifactRefPart(input?: object): object | null;
export function buildAgentWebUiConversationEnqueueFrame(text: unknown, options?: object): object | null;
export function buildAgentWebUiEventsReadFrame(options?: object): object;
export function buildAgentWebUiSurfaceAffordancesFrame(options?: object): object;
export function buildAgentWebUiSopSummaryFrame(options?: object): object;
export function buildAgentWebUiInboxSummaryFrame(options?: object): object;
export function buildAgentWebUiDelegationSummaryFrame(options?: object): object;
export function buildAgentWebUiMailboxSummaryFrame(options?: object): object;
export function buildAgentWebUiSchedulerSummaryFrame(options?: object): object;
export function buildAgentWebUiTaskLifecycleSummaryFrame(options?: object): object;
export function buildAgentWebUiHelpText(): string;
export function buildAgentWebUiConversationSendFrame(text: unknown, options?: object): object | null;
export function buildAgentWebUiConversationSteerFrame(text: unknown, options?: object): object | null;
export function buildAgentWebUiSubscribeFrame(options?: object): object;
export function isAgentWebUiProtocolFrame(frame: unknown): boolean;
export function findAgentWebUiCommand(rawCommand: unknown): AgentWebUiCommand | null;
export function filterAgentWebUiCommands(query?: unknown): AgentWebUiCommand[];
export function buildAgentWebUiOperatorInputAction(text: unknown, options?: object): object | null;
export function unwrapNarsClientEvent(message: unknown): any;
export function normalizeNarsClientProjectionVerbosity(verbosity?: unknown): NarsClientProjectionVerbosity;
export function isRoutineHealthyNarsSessionHealth(event: unknown): boolean;
export function classifyNarsClientEventProjection(projection: unknown): NarsClientProjectionClass;
export function shouldProjectNarsClientProjection(projection: unknown, options?: { verbosity?: unknown; includeStateSamples?: boolean }): boolean;
export function isRoutineStateSampleProjection(projection: unknown): boolean;
export function shouldProjectNarsClientEvent(message: unknown, options?: { verbosity?: unknown; includeStateSamples?: boolean }): boolean;
export function projectNarsClientEvent(message: unknown): NarsClientProjection;
export function buildNarsAttachCommands(options?: { eventEndpoint?: string; healthEndpoint?: string }): object;
