/**
 * Browser-render helper for task graph viewing.
 *
 * Creates Mermaid source + HTML wrapper artifacts in a temp directory,
 * and attempts to open the result in a browser.
 *
 * Operator-facing path: generates renderable artifacts, opens browser.
 * Headless fallback: artifacts are still created, paths are reported.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { executeOperatorProjectionOpenRequest } from '@narada2/process-launch-posture';

export interface RenderArtifacts {
  /** Directory containing the artifacts */
  artifactDir: string;
  /** Path to the Mermaid source file */
  mermaidPath: string;
  /** Path to the HTML wrapper file */
  htmlPath: string;
  /** Whether the browser was successfully opened */
  opened: boolean;
  /** Human-readable message about what happened */
  message: string;
  /** Governed request record for the operator projection open, when applicable */
  operatorProjectionOpenRequest?: Record<string, unknown>;
}

/**
 * Build an HTML wrapper that renders the given Mermaid diagram
 * using the Mermaid.js CDN.
 */
export function buildMermaidHtml(mermaidSource: string, title: string): string {
  const escapedSource = mermaidSource
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; margin: 0; padding: 2rem; background: #f5f5f5; }
    .container { max-width: 1200px; margin: 0 auto; background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    h1 { margin-top: 0; font-size: 1.25rem; color: #333; }
    .mermaid { display: flex; justify-content: center; }
    .meta { margin-top: 1rem; font-size: 0.75rem; color: #666; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${escapeHtml(title)}</h1>
    <pre class="mermaid">${escapedSource}</pre>
    <div class="meta">Generated by narada task graph</div>
  </div>
  <script>
    mermaid.initialize({ startOnLoad: true, theme: 'default' });
  </script>
</body>
</html>
`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Write Mermaid source and HTML wrapper to a timestamped temp directory.
 */
export async function writeRenderArtifacts(
  mermaidSource: string,
  title: string,
): Promise<{ artifactDir: string; mermaidPath: string; htmlPath: string }> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const artifactDir = join(tmpdir(), `narada-task-graph-${timestamp}`);
  await mkdir(artifactDir, { recursive: true });

  const mermaidPath = join(artifactDir, 'graph.mmd');
  const htmlPath = join(artifactDir, 'index.html');

  await writeFile(mermaidPath, mermaidSource, 'utf8');
  await writeFile(htmlPath, buildMermaidHtml(mermaidSource, title), 'utf8');

  return { artifactDir, mermaidPath, htmlPath };
}

/**
 * Request opening the given file path in the default browser.
 * The posture wrapper hides helper consoles on Windows; this legacy boolean API
 * only reports that the request was queued.
 */
export function openBrowser(filePath: string): boolean {
  void executeOperatorProjectionOpenRequest({
    projection_kind: 'browser_url',
    target_ref: filePath,
    purpose: 'artifact_browser_render',
    caller: { package: '@narada2/cli', command: 'task graph view', module: 'lib/browser-render' },
    mode: 'execute',
    policy: { allow_visible_host_effect: true },
  }).catch(() => {});
  return true;
}

async function requestOpenBrowser(filePath: string): Promise<Record<string, unknown>> {
  return await executeOperatorProjectionOpenRequest({
    projection_kind: 'browser_url',
    target_ref: filePath,
    purpose: 'artifact_browser_render',
    caller: { package: '@narada2/cli', command: 'task graph view', module: 'lib/browser-render' },
    mode: 'execute',
    policy: { allow_visible_host_effect: true },
  }) as unknown as Record<string, unknown>;
}

/**
 * Full operator-facing render path: write artifacts and optionally open browser.
 *
 * @param mermaidSource - The Mermaid diagram source
 * @param title - Title for the HTML page
 * @param shouldOpen - Whether to attempt browser open
 * @returns RenderArtifacts describing what was created and whether it was opened
 */
export async function renderAndMaybeOpen(
  mermaidSource: string,
  title: string,
  shouldOpen: boolean,
): Promise<RenderArtifacts> {
  const { artifactDir, mermaidPath, htmlPath } = await writeRenderArtifacts(mermaidSource, title);

  if (!shouldOpen) {
    const operatorProjectionOpenRequest = await executeOperatorProjectionOpenRequest({
      projection_kind: 'browser_url',
      target_ref: htmlPath,
      purpose: 'artifact_browser_render',
      caller: { package: '@narada2/cli', command: 'task graph view', module: 'lib/browser-render' },
      mode: 'execute',
      policy: { allow_visible_host_effect: false, suppress_reason: 'operator_policy:no_open' },
    }) as unknown as Record<string, unknown>;
    return {
      artifactDir,
      mermaidPath,
      htmlPath,
      opened: false,
      message: `Artifacts written to ${artifactDir}`,
      operatorProjectionOpenRequest,
    };
  }

  const isHeadless = detectHeadless();
  if (isHeadless) {
    const operatorProjectionOpenRequest = await executeOperatorProjectionOpenRequest({
      projection_kind: 'browser_url',
      target_ref: htmlPath,
      purpose: 'artifact_browser_render',
      caller: { package: '@narada2/cli', command: 'task graph view', module: 'lib/browser-render' },
      mode: 'execute',
      policy: { allow_visible_host_effect: true, suppress_reason: 'headless_environment' },
    }) as unknown as Record<string, unknown>;
    return {
      artifactDir,
      mermaidPath,
      htmlPath,
      opened: false,
      message: `Headless environment detected. Artifacts written to ${artifactDir}`,
      operatorProjectionOpenRequest,
    };
  }

  const operatorProjectionOpenRequest = await requestOpenBrowser(htmlPath);
  const opened = operatorProjectionOpenRequest.status === 'opened';
  return {
    artifactDir,
    mermaidPath,
    htmlPath,
    opened,
    message: opened
      ? `Opened ${htmlPath}`
      : `Could not open browser. Artifacts written to ${artifactDir}`,
    operatorProjectionOpenRequest,
  };
}

/**
 * Detect whether we are likely in a headless environment
 * where opening a browser would not work.
 */
function detectHeadless(): boolean {
  // Explicit opt-out
  if (process.env.NARADA_NO_BROWSER) return true;

  // Common CI/headless indicators
  if (process.env.CI) return true;
  if (process.env.HEADLESS) return true;

  // Linux without DISPLAY is typically headless
  if (process.platform === 'linux' && !process.env.DISPLAY) return true;

  return false;
}
