export const OPERATOR_INPUT_PHASES = Object.freeze({
  DRAFT: 'draft',
  SUBMITTING: 'submitting',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
  QUEUED: 'queued',
  STEERING: 'steering',
  COMPLETED: 'completed',
  FAILED: 'failed',
  SENT: 'sent',
  TIMED_OUT: 'timed_out',
  RELAY_PENDING: 'relay_pending',
  REVIEWING: 'reviewing',
  RETRIED: 'retried',
  LATE_RECONCILED: 'late_reconciled',
  DISCARDED: 'discarded',
  EXPIRED: 'expired',
} as const);

export type OperatorInputPhase = typeof OPERATOR_INPUT_PHASES[keyof typeof OPERATOR_INPUT_PHASES];

export type OperatorInputLifecycle = {
  phase: string;
  updated_at?: string;
  [key: string]: unknown;
};

export const OPERATOR_INPUT_TRANSITIONS: Readonly<Record<OperatorInputPhase, readonly OperatorInputPhase[]>> = Object.freeze({
  [OPERATOR_INPUT_PHASES.DRAFT]: Object.freeze([
    OPERATOR_INPUT_PHASES.SUBMITTING, OPERATOR_INPUT_PHASES.ACCEPTED,
    OPERATOR_INPUT_PHASES.STEERING, OPERATOR_INPUT_PHASES.COMPLETED,
    OPERATOR_INPUT_PHASES.REJECTED, OPERATOR_INPUT_PHASES.FAILED,
    OPERATOR_INPUT_PHASES.TIMED_OUT, OPERATOR_INPUT_PHASES.RELAY_PENDING,
    OPERATOR_INPUT_PHASES.REVIEWING, OPERATOR_INPUT_PHASES.DISCARDED,
    OPERATOR_INPUT_PHASES.EXPIRED,
  ]),
  [OPERATOR_INPUT_PHASES.SUBMITTING]: Object.freeze([
    OPERATOR_INPUT_PHASES.ACCEPTED, OPERATOR_INPUT_PHASES.STEERING,
    OPERATOR_INPUT_PHASES.COMPLETED, OPERATOR_INPUT_PHASES.REJECTED,
    OPERATOR_INPUT_PHASES.FAILED, OPERATOR_INPUT_PHASES.TIMED_OUT,
    OPERATOR_INPUT_PHASES.RELAY_PENDING,
  ]),
  [OPERATOR_INPUT_PHASES.RELAY_PENDING]: Object.freeze([
    OPERATOR_INPUT_PHASES.ACCEPTED, OPERATOR_INPUT_PHASES.QUEUED,
    OPERATOR_INPUT_PHASES.STEERING, OPERATOR_INPUT_PHASES.COMPLETED,
    OPERATOR_INPUT_PHASES.REJECTED, OPERATOR_INPUT_PHASES.FAILED,
    OPERATOR_INPUT_PHASES.TIMED_OUT, OPERATOR_INPUT_PHASES.REVIEWING,
  ]),
  [OPERATOR_INPUT_PHASES.ACCEPTED]: Object.freeze([
    OPERATOR_INPUT_PHASES.QUEUED, OPERATOR_INPUT_PHASES.STEERING,
    OPERATOR_INPUT_PHASES.COMPLETED, OPERATOR_INPUT_PHASES.REJECTED,
    OPERATOR_INPUT_PHASES.FAILED,
  ]),
  [OPERATOR_INPUT_PHASES.QUEUED]: Object.freeze([
    OPERATOR_INPUT_PHASES.STEERING, OPERATOR_INPUT_PHASES.COMPLETED,
    OPERATOR_INPUT_PHASES.REJECTED, OPERATOR_INPUT_PHASES.FAILED,
  ]),
  [OPERATOR_INPUT_PHASES.STEERING]: Object.freeze([
    OPERATOR_INPUT_PHASES.COMPLETED, OPERATOR_INPUT_PHASES.REJECTED,
    OPERATOR_INPUT_PHASES.FAILED,
  ]),
  [OPERATOR_INPUT_PHASES.SENT]: Object.freeze([
    OPERATOR_INPUT_PHASES.RELAY_PENDING, OPERATOR_INPUT_PHASES.TIMED_OUT,
    OPERATOR_INPUT_PHASES.REVIEWING,
  ]),
  [OPERATOR_INPUT_PHASES.TIMED_OUT]: Object.freeze([
    OPERATOR_INPUT_PHASES.ACCEPTED, OPERATOR_INPUT_PHASES.QUEUED,
    OPERATOR_INPUT_PHASES.STEERING, OPERATOR_INPUT_PHASES.COMPLETED,
    OPERATOR_INPUT_PHASES.REJECTED, OPERATOR_INPUT_PHASES.FAILED,
    OPERATOR_INPUT_PHASES.RELAY_PENDING, OPERATOR_INPUT_PHASES.REVIEWING,
    OPERATOR_INPUT_PHASES.RETRIED, OPERATOR_INPUT_PHASES.LATE_RECONCILED,
    OPERATOR_INPUT_PHASES.DISCARDED, OPERATOR_INPUT_PHASES.EXPIRED,
  ]),
  [OPERATOR_INPUT_PHASES.REVIEWING]: Object.freeze([
    OPERATOR_INPUT_PHASES.RETRIED, OPERATOR_INPUT_PHASES.LATE_RECONCILED,
    OPERATOR_INPUT_PHASES.DISCARDED, OPERATOR_INPUT_PHASES.EXPIRED,
    OPERATOR_INPUT_PHASES.ACCEPTED, OPERATOR_INPUT_PHASES.QUEUED,
    OPERATOR_INPUT_PHASES.STEERING, OPERATOR_INPUT_PHASES.COMPLETED,
    OPERATOR_INPUT_PHASES.REJECTED, OPERATOR_INPUT_PHASES.FAILED,
  ]),
  [OPERATOR_INPUT_PHASES.RETRIED]: Object.freeze([]),
  [OPERATOR_INPUT_PHASES.LATE_RECONCILED]: Object.freeze([]),
  [OPERATOR_INPUT_PHASES.DISCARDED]: Object.freeze([]),
  [OPERATOR_INPUT_PHASES.EXPIRED]: Object.freeze([]),
  [OPERATOR_INPUT_PHASES.COMPLETED]: Object.freeze([]),
  [OPERATOR_INPUT_PHASES.REJECTED]: Object.freeze([]),
  [OPERATOR_INPUT_PHASES.FAILED]: Object.freeze([]),
});

function isOperatorInputPhase(value: unknown): value is OperatorInputPhase {
  return typeof value === 'string'
    && (Object.values(OPERATOR_INPUT_PHASES) as readonly string[]).includes(value);
}

export function canTransitionOperatorInput(from: unknown, to: unknown): boolean {
  if (from === to) return isOperatorInputPhase(from);
  return isOperatorInputPhase(from)
    && isOperatorInputPhase(to)
    && OPERATOR_INPUT_TRANSITIONS[from].includes(to);
}

export function transitionOperatorInputLifecycle(
  lifecycle: OperatorInputLifecycle | null | undefined,
  phase: string,
  updatedAt = new Date().toISOString(),
): boolean {
  if (!lifecycle || !canTransitionOperatorInput(lifecycle.phase, phase)) return false;
  lifecycle.phase = phase;
  lifecycle.updated_at = updatedAt;
  return true;
}
