export const CARRIER_SCRIPT_SURFACES: any = Object.freeze({
  "commands": {
    "directory": "scripts/commands",
    "role": "operator-facing command clients and mutation entrypoints",
    "canonical_files": [
      "scripts/commands/cloudflare-carrier-continuation-resume.ts",
      "scripts/commands/cloudflare-carrier-deploy-check.ts",
      "scripts/commands/cloudflare-carrier-local-ingress-evidence.ts",
      "scripts/commands/cloudflare-carrier-local-ingress-request.ts",
      "scripts/commands/cloudflare-carrier-operation-create.ts",
      "scripts/commands/cloudflare-carrier-operation-status-put.ts",
      "scripts/commands/cloudflare-carrier-operator-session-capture.ts",
      "scripts/commands/cloudflare-carrier-repository-publication-admission.ts",
      "scripts/commands/cloudflare-carrier-repository-publication-cloudflare-execution.ts",
      "scripts/commands/cloudflare-carrier-repository-publication-evidence.ts",
      "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-preflight.ts",
      "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-put.ts",
      "scripts/commands/cloudflare-carrier-repository-publication-request.ts",
      "scripts/commands/cloudflare-carrier-repository-publication-secret-put.ts",
      "scripts/commands/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.ts",
      "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.ts",
      "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-execute.ts",
      "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-request.ts",
      "scripts/commands/cloudflare-carrier-site-continuity-loop-report.ts",
      "scripts/commands/cloudflare-carrier-site-continuity-publish.ts",
      "scripts/commands/cloudflare-carrier-site-file-change-proposal.ts",
      "scripts/commands/cloudflare-carrier-site-file-materialization.ts",
      "scripts/commands/cloudflare-carrier-site-membership-put.ts",
      "scripts/commands/cloudflare-carrier-task-lifecycle-changed-file-evidence.ts",
      "scripts/commands/cloudflare-carrier-task-lifecycle-claim.ts",
      "scripts/commands/cloudflare-carrier-task-lifecycle-create-from-directive-intent.ts",
      "scripts/commands/cloudflare-carrier-task-lifecycle-create.ts",
      "scripts/commands/cloudflare-carrier-task-lifecycle-finish.ts",
      "scripts/commands/cloudflare-carrier-task-lifecycle-report.ts",
      "scripts/commands/cloudflare-intelligence-deploy.ts",
      "scripts/commands/generate-cloudflare-intelligence-catalog.ts"
    ],
    "compatibility_policy": "flat scripts remain stable aliases for existing package commands"
  },
  "read_models": {
    "directory": "scripts/read-models",
    "role": "authenticated product read clients and response projections",
    "canonical_files": [
      "scripts/read-models/cloudflare-carrier-authority-transfer-read.ts",
      "scripts/read-models/cloudflare-carrier-local-ingress-evidence-read.ts",
      "scripts/read-models/cloudflare-carrier-local-ingress-request-read.ts",
      "scripts/read-models/cloudflare-carrier-mailbox-draft-reply-proposal-read.ts",
      "scripts/read-models/cloudflare-carrier-mailbox-outlook-draft-read.ts",
      "scripts/read-models/cloudflare-carrier-mailbox-send-accepted-read.ts",
      "scripts/read-models/cloudflare-carrier-mailbox-send-confirmation-read.ts",
      "scripts/read-models/cloudflare-carrier-operation-evidence-read.ts",
      "scripts/read-models/cloudflare-carrier-operation-focus-review.ts",
      "scripts/read-models/cloudflare-carrier-operation-persistence-read.ts",
      "scripts/read-models/cloudflare-carrier-operation-recovery-read.ts",
      "scripts/read-models/cloudflare-carrier-operation-scope-read.ts",
      "scripts/read-models/cloudflare-carrier-operator-session-status.ts",
      "scripts/read-models/cloudflare-carrier-product-read.ts",
      "scripts/read-models/cloudflare-carrier-repository-publication-read.ts",
      "scripts/read-models/cloudflare-carrier-repository-publication-readiness.ts",
      "scripts/read-models/cloudflare-carrier-repository-publication-request-review.ts",
      "scripts/read-models/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.ts",
      "scripts/read-models/cloudflare-carrier-session-evidence-read.ts",
      "scripts/read-models/cloudflare-carrier-site-authority-read.ts",
      "scripts/read-models/cloudflare-carrier-site-file-change-proposal-review.ts",
      "scripts/read-models/cloudflare-carrier-site-file-materialization-read.ts",
      "scripts/read-models/cloudflare-carrier-site-registry-projection.ts",
      "scripts/read-models/cloudflare-carrier-site-scope-read.ts",
      "scripts/read-models/cloudflare-carrier-task-lifecycle-read.ts",
      "scripts/read-models/cloudflare-carrier-webhook-delay-shadow-read.ts"
    ],
    "compatibility_policy": "flat product-read entrypoint remains a compatibility alias"
  },
  "workflows": {
    "directory": "scripts/workflows",
    "role": "live carrier workflows and smoke-test orchestration",
    "canonical_files": [
      "scripts/workflows/cloudflare-carrier-authority-transfer-readiness-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-control-plane-convergence-live.ts",
      "scripts/workflows/cloudflare-carrier-directive-delivery-review.ts",
      "scripts/workflows/cloudflare-carrier-durability-coherence-live.ts",
      "scripts/workflows/cloudflare-carrier-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-local-ingress-provider-liveness-read.ts",
      "scripts/workflows/cloudflare-carrier-local-ingress-request-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-mailbox-readback-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-mailbox-send-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-mailbox-status-shadow-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-mailbox-status-source-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-operation-continuation-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-operation-continuity-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-operation-convergence-live.ts",
      "scripts/workflows/cloudflare-carrier-operation-focus-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-operation-lifecycle-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-operation-next-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-operation-session-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-posture-coherence-live.ts",
      "scripts/workflows/cloudflare-carrier-provider-liveness-refresh.ts",
      "scripts/workflows/cloudflare-carrier-provider-liveness-scheduled-task.ts",
      "scripts/workflows/cloudflare-carrier-provider-liveness-scheduler.ts",
      "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-repository-publication-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-repository-publication-provider-liveness-read.ts",
      "scripts/workflows/cloudflare-carrier-repository-publication-readback-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-repository-publication-readiness-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-resident-dispatch-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-resident-loop-shadow-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-site-action-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-site-file-change-proposal-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-site-file-materialization-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-site-focus-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-site-next-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-claim-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-create-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-finish-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-next-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-report-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-shadow-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-task-lifecycle-workflow-live.ts",
      "scripts/workflows/cloudflare-carrier-webhook-delay-direct-source-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-webhook-delay-directive-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-webhook-delay-remote-source-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.ts",
      "scripts/workflows/cloudflare-carrier-webhook-delay-shadow-live-smoke.ts",
      "scripts/workflows/cloudflare-site-continuity-bindings.ts",
      "scripts/workflows/cloudflare-site-continuity-scheduled-task.ts",
      "scripts/workflows/cloudflare-site-continuity-scheduler.ts",
      "scripts/workflows/cloudflare-site-continuity-sync.ts"
    ],
    "compatibility_policy": "flat live-workflow entrypoints remain compatibility aliases"
  },
  "shared": {
    "directory": "scripts/shared",
    "role": "cross-surface authentication, HTTP, and explicit ownership metadata",
    "canonical_files": [
      "scripts/shared/carrier-script-surfaces.ts",
      "scripts/shared/cloudflare-carrier-auth-http.ts"
    ],
    "compatibility_policy": "shared modules have no public command alias"
  },
  "contracts": {
    "directory": "scripts/contracts",
    "role": "contract-test modules and suite orchestration",
    "canonical_files": [
      "scripts/contracts/cloudflare-carrier-authority-transfer-read.test.ts",
      "scripts/contracts/cloudflare-carrier-authority-transfer-readiness-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-continuation-resume.test.ts",
      "scripts/contracts/cloudflare-carrier-control-plane-convergence-live.test.ts",
      "scripts/contracts/cloudflare-carrier-directive-delivery-review.test.ts",
      "scripts/contracts/cloudflare-carrier-durability-coherence-live.test.ts",
      "scripts/contracts/cloudflare-carrier-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-local-ingress-evidence-read.test.ts",
      "scripts/contracts/cloudflare-carrier-local-ingress-evidence.test.ts",
      "scripts/contracts/cloudflare-carrier-local-ingress-provider-liveness-read.test.ts",
      "scripts/contracts/cloudflare-carrier-local-ingress-request-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-local-ingress-request-read.test.ts",
      "scripts/contracts/cloudflare-carrier-local-ingress-request.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-read.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-read.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-readback-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-send-accepted-read.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-send-confirmation-read.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-send-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-status-shadow-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-mailbox-status-source-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-continuation-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-continuity-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-convergence-live.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-create.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-evidence-read.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-focus-review.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-focus-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-lifecycle-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-next-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-persistence-read.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-recovery-read.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-scope-read.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-session-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-operation-status-put.test.ts",
      "scripts/contracts/cloudflare-carrier-operator-session-capture.test.ts",
      "scripts/contracts/cloudflare-carrier-posture-coherence-live.test.ts",
      "scripts/contracts/cloudflare-carrier-product-read.test.ts",
      "scripts/contracts/cloudflare-carrier-provider-liveness-refresh-live.test.ts",
      "scripts/contracts/cloudflare-carrier-provider-liveness-refresh.test.ts",
      "scripts/contracts/cloudflare-carrier-provider-liveness-scheduler.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-admission.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-execution.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-evidence.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-preflight.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-put.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-provider-liveness-read.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-read.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-readback-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-readiness-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-readiness.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-request-review.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-request.test.ts",
      "scripts/contracts/cloudflare-carrier-repository-publication-secret-put.test.ts",
      "scripts/contracts/cloudflare-carrier-resident-dispatch-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.test.ts",
      "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.test.ts",
      "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.test.ts",
      "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-execute.test.ts",
      "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-request.test.ts",
      "scripts/contracts/cloudflare-carrier-resident-loop-shadow-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-script-manifest.test.ts",
      "scripts/contracts/cloudflare-carrier-session-evidence-read.test.ts",
      "scripts/contracts/cloudflare-carrier-site-action-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-site-authority-read.test.ts",
      "scripts/contracts/cloudflare-carrier-site-continuity-loop-report.test.ts",
      "scripts/contracts/cloudflare-carrier-site-continuity-publish.test.ts",
      "scripts/contracts/cloudflare-carrier-site-file-change-proposal-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-site-file-change-proposal-review.test.ts",
      "scripts/contracts/cloudflare-carrier-site-file-change-proposal.test.ts",
      "scripts/contracts/cloudflare-carrier-site-file-materialization-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-site-file-materialization-read.test.ts",
      "scripts/contracts/cloudflare-carrier-site-file-materialization.test.ts",
      "scripts/contracts/cloudflare-carrier-site-focus-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-site-membership-put.test.ts",
      "scripts/contracts/cloudflare-carrier-site-next-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-site-registry-projection.test.ts",
      "scripts/contracts/cloudflare-carrier-site-scope-read.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-claim-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-claim.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-create-from-directive-intent.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-create-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-create.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-finish-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-finish.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-next-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-read.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-report-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-report.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-shadow-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-task-lifecycle-workflow-live.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-direct-source-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-directive-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-remote-source-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-live-smoke.test.ts",
      "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-read.test.ts",
      "scripts/contracts/cloudflare-intelligence-deploy.test.ts",
      "scripts/contracts/cloudflare-site-continuity-bindings.test.ts",
      "scripts/contracts/cloudflare-site-continuity-scheduled-task.test.ts",
      "scripts/contracts/cloudflare-site-continuity-scheduler.test.ts",
      "scripts/contracts/cloudflare-site-continuity-sync.test.ts",
      "scripts/contracts/contract-suite.test.ts",
      "scripts/contracts/live-suite.test.ts",
      "scripts/contracts/suite-loader.ts",
      "scripts/contracts/unit-suite.test.ts"
    ],
    "compatibility_policy": "individual contract files remain directly runnable"
  }
});

export const CARRIER_SCRIPT_SURFACE_IDS = Object.freeze(Object.keys(CARRIER_SCRIPT_SURFACES));
export const CARRIER_SCRIPT_OWNERSHIP: any = Object.freeze({
  "scripts/cloudflare-carrier-authority-transfer-read.ts": "scripts/read-models/cloudflare-carrier-authority-transfer-read.ts",
  "scripts/cloudflare-carrier-authority-transfer-read.test.ts": "scripts/contracts/cloudflare-carrier-authority-transfer-read.test.ts",
  "scripts/cloudflare-carrier-authority-transfer-readiness-live-smoke.ts": "scripts/workflows/cloudflare-carrier-authority-transfer-readiness-live-smoke.ts",
  "scripts/cloudflare-carrier-authority-transfer-readiness-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-authority-transfer-readiness-live-smoke.test.ts",
  "scripts/cloudflare-carrier-continuation-resume.ts": "scripts/commands/cloudflare-carrier-continuation-resume.ts",
  "scripts/cloudflare-carrier-continuation-resume.test.ts": "scripts/contracts/cloudflare-carrier-continuation-resume.test.ts",
  "scripts/cloudflare-carrier-control-plane-convergence-live.ts": "scripts/workflows/cloudflare-carrier-control-plane-convergence-live.ts",
  "scripts/cloudflare-carrier-control-plane-convergence-live.test.ts": "scripts/contracts/cloudflare-carrier-control-plane-convergence-live.test.ts",
  "scripts/cloudflare-carrier-deploy-check.ts": "scripts/commands/cloudflare-carrier-deploy-check.ts",
  "scripts/cloudflare-carrier-directive-delivery-review.ts": "scripts/workflows/cloudflare-carrier-directive-delivery-review.ts",
  "scripts/cloudflare-carrier-directive-delivery-review.test.ts": "scripts/contracts/cloudflare-carrier-directive-delivery-review.test.ts",
  "scripts/cloudflare-carrier-durability-coherence-live.ts": "scripts/workflows/cloudflare-carrier-durability-coherence-live.ts",
  "scripts/cloudflare-carrier-durability-coherence-live.test.ts": "scripts/contracts/cloudflare-carrier-durability-coherence-live.test.ts",
  "scripts/cloudflare-carrier-live-smoke.ts": "scripts/workflows/cloudflare-carrier-live-smoke.ts",
  "scripts/cloudflare-carrier-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-live-smoke.test.ts",
  "scripts/cloudflare-carrier-local-ingress-evidence-read.ts": "scripts/read-models/cloudflare-carrier-local-ingress-evidence-read.ts",
  "scripts/cloudflare-carrier-local-ingress-evidence-read.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-evidence-read.test.ts",
  "scripts/cloudflare-carrier-local-ingress-evidence.ts": "scripts/commands/cloudflare-carrier-local-ingress-evidence.ts",
  "scripts/cloudflare-carrier-local-ingress-evidence.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-evidence.test.ts",
  "scripts/cloudflare-carrier-local-ingress-provider-liveness-read.ts": "scripts/workflows/cloudflare-carrier-local-ingress-provider-liveness-read.ts",
  "scripts/cloudflare-carrier-local-ingress-provider-liveness-read.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-provider-liveness-read.test.ts",
  "scripts/cloudflare-carrier-local-ingress-request-live-smoke.ts": "scripts/workflows/cloudflare-carrier-local-ingress-request-live-smoke.ts",
  "scripts/cloudflare-carrier-local-ingress-request-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-request-live-smoke.test.ts",
  "scripts/cloudflare-carrier-local-ingress-request-read.ts": "scripts/read-models/cloudflare-carrier-local-ingress-request-read.ts",
  "scripts/cloudflare-carrier-local-ingress-request-read.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-request-read.test.ts",
  "scripts/cloudflare-carrier-local-ingress-request.ts": "scripts/commands/cloudflare-carrier-local-ingress-request.ts",
  "scripts/cloudflare-carrier-local-ingress-request.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-request.test.ts",
  "scripts/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.ts",
  "scripts/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.test.ts",
  "scripts/cloudflare-carrier-mailbox-draft-reply-proposal-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-draft-reply-proposal-read.ts",
  "scripts/cloudflare-carrier-mailbox-draft-reply-proposal-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-read.test.ts",
  "scripts/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.ts",
  "scripts/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.test.ts",
  "scripts/cloudflare-carrier-mailbox-outlook-draft-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-outlook-draft-read.ts",
  "scripts/cloudflare-carrier-mailbox-outlook-draft-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-read.test.ts",
  "scripts/cloudflare-carrier-mailbox-readback-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-readback-live-smoke.ts",
  "scripts/cloudflare-carrier-mailbox-readback-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-readback-live-smoke.test.ts",
  "scripts/cloudflare-carrier-mailbox-send-accepted-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-send-accepted-read.ts",
  "scripts/cloudflare-carrier-mailbox-send-accepted-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-send-accepted-read.test.ts",
  "scripts/cloudflare-carrier-mailbox-send-confirmation-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-send-confirmation-read.ts",
  "scripts/cloudflare-carrier-mailbox-send-confirmation-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-send-confirmation-read.test.ts",
  "scripts/cloudflare-carrier-mailbox-send-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-send-live-smoke.ts",
  "scripts/cloudflare-carrier-mailbox-send-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-send-live-smoke.test.ts",
  "scripts/cloudflare-carrier-mailbox-status-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-status-shadow-live-smoke.ts",
  "scripts/cloudflare-carrier-mailbox-status-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-status-shadow-live-smoke.test.ts",
  "scripts/cloudflare-carrier-mailbox-status-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-status-source-live-smoke.ts",
  "scripts/cloudflare-carrier-mailbox-status-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-status-source-live-smoke.test.ts",
  "scripts/cloudflare-carrier-operation-continuation-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-continuation-workflow-live.ts",
  "scripts/cloudflare-carrier-operation-continuation-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-continuation-workflow-live.test.ts",
  "scripts/cloudflare-carrier-operation-continuity-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-continuity-workflow-live.ts",
  "scripts/cloudflare-carrier-operation-continuity-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-continuity-workflow-live.test.ts",
  "scripts/cloudflare-carrier-operation-convergence-live.ts": "scripts/workflows/cloudflare-carrier-operation-convergence-live.ts",
  "scripts/cloudflare-carrier-operation-convergence-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-convergence-live.test.ts",
  "scripts/cloudflare-carrier-operation-create.ts": "scripts/commands/cloudflare-carrier-operation-create.ts",
  "scripts/cloudflare-carrier-operation-create.test.ts": "scripts/contracts/cloudflare-carrier-operation-create.test.ts",
  "scripts/cloudflare-carrier-operation-evidence-read.ts": "scripts/read-models/cloudflare-carrier-operation-evidence-read.ts",
  "scripts/cloudflare-carrier-operation-evidence-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-evidence-read.test.ts",
  "scripts/cloudflare-carrier-operation-focus-review.ts": "scripts/read-models/cloudflare-carrier-operation-focus-review.ts",
  "scripts/cloudflare-carrier-operation-focus-review.test.ts": "scripts/contracts/cloudflare-carrier-operation-focus-review.test.ts",
  "scripts/cloudflare-carrier-operation-focus-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-focus-workflow-live.ts",
  "scripts/cloudflare-carrier-operation-focus-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-focus-workflow-live.test.ts",
  "scripts/cloudflare-carrier-operation-lifecycle-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-lifecycle-workflow-live.ts",
  "scripts/cloudflare-carrier-operation-lifecycle-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-lifecycle-workflow-live.test.ts",
  "scripts/cloudflare-carrier-operation-next-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-next-workflow-live.ts",
  "scripts/cloudflare-carrier-operation-next-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-next-workflow-live.test.ts",
  "scripts/cloudflare-carrier-operation-persistence-read.ts": "scripts/read-models/cloudflare-carrier-operation-persistence-read.ts",
  "scripts/cloudflare-carrier-operation-persistence-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-persistence-read.test.ts",
  "scripts/cloudflare-carrier-operation-recovery-read.ts": "scripts/read-models/cloudflare-carrier-operation-recovery-read.ts",
  "scripts/cloudflare-carrier-operation-recovery-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-recovery-read.test.ts",
  "scripts/cloudflare-carrier-operation-scope-read.ts": "scripts/read-models/cloudflare-carrier-operation-scope-read.ts",
  "scripts/cloudflare-carrier-operation-scope-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-scope-read.test.ts",
  "scripts/cloudflare-carrier-operation-session-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-session-workflow-live.ts",
  "scripts/cloudflare-carrier-operation-session-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-session-workflow-live.test.ts",
  "scripts/cloudflare-carrier-operation-status-put.ts": "scripts/commands/cloudflare-carrier-operation-status-put.ts",
  "scripts/cloudflare-carrier-operation-status-put.test.ts": "scripts/contracts/cloudflare-carrier-operation-status-put.test.ts",
  "scripts/cloudflare-carrier-operator-session-capture.ts": "scripts/commands/cloudflare-carrier-operator-session-capture.ts",
  "scripts/cloudflare-carrier-operator-session-capture.test.ts": "scripts/contracts/cloudflare-carrier-operator-session-capture.test.ts",
  "scripts/cloudflare-carrier-operator-session-status.ts": "scripts/read-models/cloudflare-carrier-operator-session-status.ts",
  "scripts/cloudflare-carrier-posture-coherence-live.ts": "scripts/workflows/cloudflare-carrier-posture-coherence-live.ts",
  "scripts/cloudflare-carrier-posture-coherence-live.test.ts": "scripts/contracts/cloudflare-carrier-posture-coherence-live.test.ts",
  "scripts/cloudflare-carrier-product-read.ts": "scripts/read-models/cloudflare-carrier-product-read.ts",
  "scripts/cloudflare-carrier-product-read.test.ts": "scripts/contracts/cloudflare-carrier-product-read.test.ts",
  "scripts/cloudflare-carrier-provider-liveness-refresh-live.test.ts": "scripts/contracts/cloudflare-carrier-provider-liveness-refresh-live.test.ts",
  "scripts/cloudflare-carrier-provider-liveness-refresh.ts": "scripts/workflows/cloudflare-carrier-provider-liveness-refresh.ts",
  "scripts/cloudflare-carrier-provider-liveness-refresh.test.ts": "scripts/contracts/cloudflare-carrier-provider-liveness-refresh.test.ts",
  "scripts/cloudflare-carrier-provider-liveness-scheduled-task.ts": "scripts/workflows/cloudflare-carrier-provider-liveness-scheduled-task.ts",
  "scripts/cloudflare-carrier-provider-liveness-scheduler.ts": "scripts/workflows/cloudflare-carrier-provider-liveness-scheduler.ts",
  "scripts/cloudflare-carrier-provider-liveness-scheduler.test.ts": "scripts/contracts/cloudflare-carrier-provider-liveness-scheduler.test.ts",
  "scripts/cloudflare-carrier-repository-publication-admission.ts": "scripts/commands/cloudflare-carrier-repository-publication-admission.ts",
  "scripts/cloudflare-carrier-repository-publication-admission.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-admission.test.ts",
  "scripts/cloudflare-carrier-repository-publication-cloudflare-execution.ts": "scripts/commands/cloudflare-carrier-repository-publication-cloudflare-execution.ts",
  "scripts/cloudflare-carrier-repository-publication-cloudflare-execution.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-execution.test.ts",
  "scripts/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.ts",
  "scripts/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.test.ts",
  "scripts/cloudflare-carrier-repository-publication-cloudflare-workflow-live.ts": "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-workflow-live.ts",
  "scripts/cloudflare-carrier-repository-publication-cloudflare-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-workflow-live.test.ts",
  "scripts/cloudflare-carrier-repository-publication-evidence.ts": "scripts/commands/cloudflare-carrier-repository-publication-evidence.ts",
  "scripts/cloudflare-carrier-repository-publication-evidence.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-evidence.test.ts",
  "scripts/cloudflare-carrier-repository-publication-github-app-secret-preflight.ts": "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-preflight.ts",
  "scripts/cloudflare-carrier-repository-publication-github-app-secret-preflight.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-preflight.test.ts",
  "scripts/cloudflare-carrier-repository-publication-github-app-secret-put.ts": "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-put.ts",
  "scripts/cloudflare-carrier-repository-publication-github-app-secret-put.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-put.test.ts",
  "scripts/cloudflare-carrier-repository-publication-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-live-smoke.ts",
  "scripts/cloudflare-carrier-repository-publication-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-live-smoke.test.ts",
  "scripts/cloudflare-carrier-repository-publication-provider-liveness-read.ts": "scripts/workflows/cloudflare-carrier-repository-publication-provider-liveness-read.ts",
  "scripts/cloudflare-carrier-repository-publication-provider-liveness-read.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-provider-liveness-read.test.ts",
  "scripts/cloudflare-carrier-repository-publication-read.ts": "scripts/read-models/cloudflare-carrier-repository-publication-read.ts",
  "scripts/cloudflare-carrier-repository-publication-read.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-read.test.ts",
  "scripts/cloudflare-carrier-repository-publication-readback-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-readback-live-smoke.ts",
  "scripts/cloudflare-carrier-repository-publication-readback-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-readback-live-smoke.test.ts",
  "scripts/cloudflare-carrier-repository-publication-readiness-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-readiness-live-smoke.ts",
  "scripts/cloudflare-carrier-repository-publication-readiness-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-readiness-live-smoke.test.ts",
  "scripts/cloudflare-carrier-repository-publication-readiness.ts": "scripts/read-models/cloudflare-carrier-repository-publication-readiness.ts",
  "scripts/cloudflare-carrier-repository-publication-readiness.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-readiness.test.ts",
  "scripts/cloudflare-carrier-repository-publication-request-review.ts": "scripts/read-models/cloudflare-carrier-repository-publication-request-review.ts",
  "scripts/cloudflare-carrier-repository-publication-request-review.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-request-review.test.ts",
  "scripts/cloudflare-carrier-repository-publication-request.ts": "scripts/commands/cloudflare-carrier-repository-publication-request.ts",
  "scripts/cloudflare-carrier-repository-publication-request.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-request.test.ts",
  "scripts/cloudflare-carrier-repository-publication-secret-put.ts": "scripts/commands/cloudflare-carrier-repository-publication-secret-put.ts",
  "scripts/cloudflare-carrier-repository-publication-secret-put.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-secret-put.test.ts",
  "scripts/cloudflare-carrier-resident-dispatch-live-smoke.ts": "scripts/workflows/cloudflare-carrier-resident-dispatch-live-smoke.ts",
  "scripts/cloudflare-carrier-resident-dispatch-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-live-smoke.test.ts",
  "scripts/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.ts",
  "scripts/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.test.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.ts": "scripts/read-models/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.test.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.test.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-execute.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-execute.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-execute.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-execute.test.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-request.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-request.ts",
  "scripts/cloudflare-carrier-resident-dispatch-windows-fallback-request.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-request.test.ts",
  "scripts/cloudflare-carrier-resident-loop-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-resident-loop-shadow-live-smoke.ts",
  "scripts/cloudflare-carrier-resident-loop-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-resident-loop-shadow-live-smoke.test.ts",
  "scripts/cloudflare-carrier-script-manifest.test.ts": "scripts/contracts/cloudflare-carrier-script-manifest.test.ts",
  "scripts/cloudflare-carrier-session-evidence-read.ts": "scripts/read-models/cloudflare-carrier-session-evidence-read.ts",
  "scripts/cloudflare-carrier-session-evidence-read.test.ts": "scripts/contracts/cloudflare-carrier-session-evidence-read.test.ts",
  "scripts/cloudflare-carrier-site-action-workflow-live.ts": "scripts/workflows/cloudflare-carrier-site-action-workflow-live.ts",
  "scripts/cloudflare-carrier-site-action-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-site-action-workflow-live.test.ts",
  "scripts/cloudflare-carrier-site-authority-read.ts": "scripts/read-models/cloudflare-carrier-site-authority-read.ts",
  "scripts/cloudflare-carrier-site-authority-read.test.ts": "scripts/contracts/cloudflare-carrier-site-authority-read.test.ts",
  "scripts/cloudflare-carrier-site-continuity-loop-report.ts": "scripts/commands/cloudflare-carrier-site-continuity-loop-report.ts",
  "scripts/cloudflare-carrier-site-continuity-loop-report.test.ts": "scripts/contracts/cloudflare-carrier-site-continuity-loop-report.test.ts",
  "scripts/cloudflare-carrier-site-continuity-publish.ts": "scripts/commands/cloudflare-carrier-site-continuity-publish.ts",
  "scripts/cloudflare-carrier-site-continuity-publish.test.ts": "scripts/contracts/cloudflare-carrier-site-continuity-publish.test.ts",
  "scripts/cloudflare-carrier-site-file-change-proposal-live-smoke.ts": "scripts/workflows/cloudflare-carrier-site-file-change-proposal-live-smoke.ts",
  "scripts/cloudflare-carrier-site-file-change-proposal-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-site-file-change-proposal-live-smoke.test.ts",
  "scripts/cloudflare-carrier-site-file-change-proposal-review.ts": "scripts/read-models/cloudflare-carrier-site-file-change-proposal-review.ts",
  "scripts/cloudflare-carrier-site-file-change-proposal-review.test.ts": "scripts/contracts/cloudflare-carrier-site-file-change-proposal-review.test.ts",
  "scripts/cloudflare-carrier-site-file-change-proposal.ts": "scripts/commands/cloudflare-carrier-site-file-change-proposal.ts",
  "scripts/cloudflare-carrier-site-file-change-proposal.test.ts": "scripts/contracts/cloudflare-carrier-site-file-change-proposal.test.ts",
  "scripts/cloudflare-carrier-site-file-materialization-live-smoke.ts": "scripts/workflows/cloudflare-carrier-site-file-materialization-live-smoke.ts",
  "scripts/cloudflare-carrier-site-file-materialization-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-site-file-materialization-live-smoke.test.ts",
  "scripts/cloudflare-carrier-site-file-materialization-read.ts": "scripts/read-models/cloudflare-carrier-site-file-materialization-read.ts",
  "scripts/cloudflare-carrier-site-file-materialization-read.test.ts": "scripts/contracts/cloudflare-carrier-site-file-materialization-read.test.ts",
  "scripts/cloudflare-carrier-site-file-materialization.ts": "scripts/commands/cloudflare-carrier-site-file-materialization.ts",
  "scripts/cloudflare-carrier-site-file-materialization.test.ts": "scripts/contracts/cloudflare-carrier-site-file-materialization.test.ts",
  "scripts/cloudflare-carrier-site-focus-workflow-live.ts": "scripts/workflows/cloudflare-carrier-site-focus-workflow-live.ts",
  "scripts/cloudflare-carrier-site-focus-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-site-focus-workflow-live.test.ts",
  "scripts/cloudflare-carrier-site-membership-put.ts": "scripts/commands/cloudflare-carrier-site-membership-put.ts",
  "scripts/cloudflare-carrier-site-membership-put.test.ts": "scripts/contracts/cloudflare-carrier-site-membership-put.test.ts",
  "scripts/cloudflare-carrier-site-next-workflow-live.ts": "scripts/workflows/cloudflare-carrier-site-next-workflow-live.ts",
  "scripts/cloudflare-carrier-site-next-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-site-next-workflow-live.test.ts",
  "scripts/cloudflare-carrier-site-registry-projection.ts": "scripts/read-models/cloudflare-carrier-site-registry-projection.ts",
  "scripts/cloudflare-carrier-site-registry-projection.test.ts": "scripts/contracts/cloudflare-carrier-site-registry-projection.test.ts",
  "scripts/cloudflare-carrier-site-scope-read.ts": "scripts/read-models/cloudflare-carrier-site-scope-read.ts",
  "scripts/cloudflare-carrier-site-scope-read.test.ts": "scripts/contracts/cloudflare-carrier-site-scope-read.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-changed-file-evidence.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-changed-file-evidence.ts",
  "scripts/cloudflare-carrier-task-lifecycle-changed-file-evidence.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-claim-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-claim-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-claim-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-claim-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-claim.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-claim.ts",
  "scripts/cloudflare-carrier-task-lifecycle-claim.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-claim.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-create-from-directive-intent.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-create-from-directive-intent.ts",
  "scripts/cloudflare-carrier-task-lifecycle-create-from-directive-intent.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-create-from-directive-intent.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-create-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-create-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-create-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-create-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-create.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-create.ts",
  "scripts/cloudflare-carrier-task-lifecycle-create.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-create.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-finish-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-finish-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-finish-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-finish-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-finish.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-finish.ts",
  "scripts/cloudflare-carrier-task-lifecycle-finish.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-finish.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-next-workflow-live.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-next-workflow-live.ts",
  "scripts/cloudflare-carrier-task-lifecycle-next-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-next-workflow-live.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-read.ts": "scripts/read-models/cloudflare-carrier-task-lifecycle-read.ts",
  "scripts/cloudflare-carrier-task-lifecycle-read.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-read.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-report-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-report-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-report-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-report-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-report.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-report.ts",
  "scripts/cloudflare-carrier-task-lifecycle-report.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-report.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-shadow-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-shadow-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.ts",
  "scripts/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.test.ts",
  "scripts/cloudflare-carrier-task-lifecycle-workflow-live.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-workflow-live.ts",
  "scripts/cloudflare-carrier-task-lifecycle-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-workflow-live.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-direct-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-direct-source-live-smoke.ts",
  "scripts/cloudflare-carrier-webhook-delay-direct-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-direct-source-live-smoke.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.ts",
  "scripts/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-directive-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-directive-live-smoke.ts",
  "scripts/cloudflare-carrier-webhook-delay-directive-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-directive-live-smoke.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.ts",
  "scripts/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-remote-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-remote-source-live-smoke.ts",
  "scripts/cloudflare-carrier-webhook-delay-remote-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-remote-source-live-smoke.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.ts",
  "scripts/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-shadow-live-smoke.ts",
  "scripts/cloudflare-carrier-webhook-delay-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-live-smoke.test.ts",
  "scripts/cloudflare-carrier-webhook-delay-shadow-read.ts": "scripts/read-models/cloudflare-carrier-webhook-delay-shadow-read.ts",
  "scripts/cloudflare-carrier-webhook-delay-shadow-read.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-read.test.ts",
  "scripts/cloudflare-intelligence-deploy.ts": "scripts/commands/cloudflare-intelligence-deploy.ts",
  "scripts/cloudflare-intelligence-deploy.test.ts": "scripts/contracts/cloudflare-intelligence-deploy.test.ts",
  "scripts/cloudflare-site-continuity-bindings.ts": "scripts/workflows/cloudflare-site-continuity-bindings.ts",
  "scripts/cloudflare-site-continuity-bindings.test.ts": "scripts/contracts/cloudflare-site-continuity-bindings.test.ts",
  "scripts/cloudflare-site-continuity-scheduled-task.ts": "scripts/workflows/cloudflare-site-continuity-scheduled-task.ts",
  "scripts/cloudflare-site-continuity-scheduled-task.test.ts": "scripts/contracts/cloudflare-site-continuity-scheduled-task.test.ts",
  "scripts/cloudflare-site-continuity-scheduler.ts": "scripts/workflows/cloudflare-site-continuity-scheduler.ts",
  "scripts/cloudflare-site-continuity-scheduler.test.ts": "scripts/contracts/cloudflare-site-continuity-scheduler.test.ts",
  "scripts/cloudflare-site-continuity-sync.ts": "scripts/workflows/cloudflare-site-continuity-sync.ts",
  "scripts/cloudflare-site-continuity-sync.test.ts": "scripts/contracts/cloudflare-site-continuity-sync.test.ts",
  "scripts/generate-cloudflare-intelligence-catalog.ts": "scripts/commands/generate-cloudflare-intelligence-catalog.ts",
  "scripts/commands/cloudflare-carrier-continuation-resume.ts": "scripts/commands/cloudflare-carrier-continuation-resume.ts",
  "scripts/commands/cloudflare-carrier-deploy-check.ts": "scripts/commands/cloudflare-carrier-deploy-check.ts",
  "scripts/commands/cloudflare-carrier-local-ingress-evidence.ts": "scripts/commands/cloudflare-carrier-local-ingress-evidence.ts",
  "scripts/commands/cloudflare-carrier-local-ingress-request.ts": "scripts/commands/cloudflare-carrier-local-ingress-request.ts",
  "scripts/commands/cloudflare-carrier-operation-create.ts": "scripts/commands/cloudflare-carrier-operation-create.ts",
  "scripts/commands/cloudflare-carrier-operation-status-put.ts": "scripts/commands/cloudflare-carrier-operation-status-put.ts",
  "scripts/commands/cloudflare-carrier-operator-session-capture.ts": "scripts/commands/cloudflare-carrier-operator-session-capture.ts",
  "scripts/commands/cloudflare-carrier-repository-publication-admission.ts": "scripts/commands/cloudflare-carrier-repository-publication-admission.ts",
  "scripts/commands/cloudflare-carrier-repository-publication-cloudflare-execution.ts": "scripts/commands/cloudflare-carrier-repository-publication-cloudflare-execution.ts",
  "scripts/commands/cloudflare-carrier-repository-publication-evidence.ts": "scripts/commands/cloudflare-carrier-repository-publication-evidence.ts",
  "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-preflight.ts": "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-preflight.ts",
  "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-put.ts": "scripts/commands/cloudflare-carrier-repository-publication-github-app-secret-put.ts",
  "scripts/commands/cloudflare-carrier-repository-publication-request.ts": "scripts/commands/cloudflare-carrier-repository-publication-request.ts",
  "scripts/commands/cloudflare-carrier-repository-publication-secret-put.ts": "scripts/commands/cloudflare-carrier-repository-publication-secret-put.ts",
  "scripts/commands/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.ts",
  "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.ts",
  "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-execute.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-execute.ts",
  "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-request.ts": "scripts/commands/cloudflare-carrier-resident-dispatch-windows-fallback-request.ts",
  "scripts/commands/cloudflare-carrier-site-continuity-loop-report.ts": "scripts/commands/cloudflare-carrier-site-continuity-loop-report.ts",
  "scripts/commands/cloudflare-carrier-site-continuity-publish.ts": "scripts/commands/cloudflare-carrier-site-continuity-publish.ts",
  "scripts/commands/cloudflare-carrier-site-file-change-proposal.ts": "scripts/commands/cloudflare-carrier-site-file-change-proposal.ts",
  "scripts/commands/cloudflare-carrier-site-file-materialization.ts": "scripts/commands/cloudflare-carrier-site-file-materialization.ts",
  "scripts/commands/cloudflare-carrier-site-membership-put.ts": "scripts/commands/cloudflare-carrier-site-membership-put.ts",
  "scripts/commands/cloudflare-carrier-task-lifecycle-changed-file-evidence.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-changed-file-evidence.ts",
  "scripts/commands/cloudflare-carrier-task-lifecycle-claim.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-claim.ts",
  "scripts/commands/cloudflare-carrier-task-lifecycle-create-from-directive-intent.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-create-from-directive-intent.ts",
  "scripts/commands/cloudflare-carrier-task-lifecycle-create.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-create.ts",
  "scripts/commands/cloudflare-carrier-task-lifecycle-finish.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-finish.ts",
  "scripts/commands/cloudflare-carrier-task-lifecycle-report.ts": "scripts/commands/cloudflare-carrier-task-lifecycle-report.ts",
  "scripts/commands/cloudflare-intelligence-deploy.ts": "scripts/commands/cloudflare-intelligence-deploy.ts",
  "scripts/commands/generate-cloudflare-intelligence-catalog.ts": "scripts/commands/generate-cloudflare-intelligence-catalog.ts",
  "scripts/read-models/cloudflare-carrier-authority-transfer-read.ts": "scripts/read-models/cloudflare-carrier-authority-transfer-read.ts",
  "scripts/read-models/cloudflare-carrier-local-ingress-evidence-read.ts": "scripts/read-models/cloudflare-carrier-local-ingress-evidence-read.ts",
  "scripts/read-models/cloudflare-carrier-local-ingress-request-read.ts": "scripts/read-models/cloudflare-carrier-local-ingress-request-read.ts",
  "scripts/read-models/cloudflare-carrier-mailbox-draft-reply-proposal-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-draft-reply-proposal-read.ts",
  "scripts/read-models/cloudflare-carrier-mailbox-outlook-draft-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-outlook-draft-read.ts",
  "scripts/read-models/cloudflare-carrier-mailbox-send-accepted-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-send-accepted-read.ts",
  "scripts/read-models/cloudflare-carrier-mailbox-send-confirmation-read.ts": "scripts/read-models/cloudflare-carrier-mailbox-send-confirmation-read.ts",
  "scripts/read-models/cloudflare-carrier-operation-evidence-read.ts": "scripts/read-models/cloudflare-carrier-operation-evidence-read.ts",
  "scripts/read-models/cloudflare-carrier-operation-focus-review.ts": "scripts/read-models/cloudflare-carrier-operation-focus-review.ts",
  "scripts/read-models/cloudflare-carrier-operation-persistence-read.ts": "scripts/read-models/cloudflare-carrier-operation-persistence-read.ts",
  "scripts/read-models/cloudflare-carrier-operation-recovery-read.ts": "scripts/read-models/cloudflare-carrier-operation-recovery-read.ts",
  "scripts/read-models/cloudflare-carrier-operation-scope-read.ts": "scripts/read-models/cloudflare-carrier-operation-scope-read.ts",
  "scripts/read-models/cloudflare-carrier-operator-session-status.ts": "scripts/read-models/cloudflare-carrier-operator-session-status.ts",
  "scripts/read-models/cloudflare-carrier-product-read.ts": "scripts/read-models/cloudflare-carrier-product-read.ts",
  "scripts/read-models/cloudflare-carrier-repository-publication-read.ts": "scripts/read-models/cloudflare-carrier-repository-publication-read.ts",
  "scripts/read-models/cloudflare-carrier-repository-publication-readiness.ts": "scripts/read-models/cloudflare-carrier-repository-publication-readiness.ts",
  "scripts/read-models/cloudflare-carrier-repository-publication-request-review.ts": "scripts/read-models/cloudflare-carrier-repository-publication-request-review.ts",
  "scripts/read-models/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.ts": "scripts/read-models/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.ts",
  "scripts/read-models/cloudflare-carrier-session-evidence-read.ts": "scripts/read-models/cloudflare-carrier-session-evidence-read.ts",
  "scripts/read-models/cloudflare-carrier-site-authority-read.ts": "scripts/read-models/cloudflare-carrier-site-authority-read.ts",
  "scripts/read-models/cloudflare-carrier-site-file-change-proposal-review.ts": "scripts/read-models/cloudflare-carrier-site-file-change-proposal-review.ts",
  "scripts/read-models/cloudflare-carrier-site-file-materialization-read.ts": "scripts/read-models/cloudflare-carrier-site-file-materialization-read.ts",
  "scripts/read-models/cloudflare-carrier-site-registry-projection.ts": "scripts/read-models/cloudflare-carrier-site-registry-projection.ts",
  "scripts/read-models/cloudflare-carrier-site-scope-read.ts": "scripts/read-models/cloudflare-carrier-site-scope-read.ts",
  "scripts/read-models/cloudflare-carrier-task-lifecycle-read.ts": "scripts/read-models/cloudflare-carrier-task-lifecycle-read.ts",
  "scripts/read-models/cloudflare-carrier-webhook-delay-shadow-read.ts": "scripts/read-models/cloudflare-carrier-webhook-delay-shadow-read.ts",
  "scripts/workflows/cloudflare-carrier-authority-transfer-readiness-live-smoke.ts": "scripts/workflows/cloudflare-carrier-authority-transfer-readiness-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-control-plane-convergence-live.ts": "scripts/workflows/cloudflare-carrier-control-plane-convergence-live.ts",
  "scripts/workflows/cloudflare-carrier-directive-delivery-review.ts": "scripts/workflows/cloudflare-carrier-directive-delivery-review.ts",
  "scripts/workflows/cloudflare-carrier-durability-coherence-live.ts": "scripts/workflows/cloudflare-carrier-durability-coherence-live.ts",
  "scripts/workflows/cloudflare-carrier-live-smoke.ts": "scripts/workflows/cloudflare-carrier-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-local-ingress-provider-liveness-read.ts": "scripts/workflows/cloudflare-carrier-local-ingress-provider-liveness-read.ts",
  "scripts/workflows/cloudflare-carrier-local-ingress-request-live-smoke.ts": "scripts/workflows/cloudflare-carrier-local-ingress-request-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-mailbox-readback-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-readback-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-mailbox-send-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-send-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-mailbox-status-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-status-shadow-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-mailbox-status-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-mailbox-status-source-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-operation-continuation-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-continuation-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-operation-continuity-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-continuity-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-operation-convergence-live.ts": "scripts/workflows/cloudflare-carrier-operation-convergence-live.ts",
  "scripts/workflows/cloudflare-carrier-operation-focus-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-focus-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-operation-lifecycle-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-lifecycle-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-operation-next-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-next-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-operation-session-workflow-live.ts": "scripts/workflows/cloudflare-carrier-operation-session-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-posture-coherence-live.ts": "scripts/workflows/cloudflare-carrier-posture-coherence-live.ts",
  "scripts/workflows/cloudflare-carrier-provider-liveness-refresh.ts": "scripts/workflows/cloudflare-carrier-provider-liveness-refresh.ts",
  "scripts/workflows/cloudflare-carrier-provider-liveness-scheduled-task.ts": "scripts/workflows/cloudflare-carrier-provider-liveness-scheduled-task.ts",
  "scripts/workflows/cloudflare-carrier-provider-liveness-scheduler.ts": "scripts/workflows/cloudflare-carrier-provider-liveness-scheduler.ts",
  "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-workflow-live.ts": "scripts/workflows/cloudflare-carrier-repository-publication-cloudflare-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-repository-publication-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-repository-publication-provider-liveness-read.ts": "scripts/workflows/cloudflare-carrier-repository-publication-provider-liveness-read.ts",
  "scripts/workflows/cloudflare-carrier-repository-publication-readback-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-readback-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-repository-publication-readiness-live-smoke.ts": "scripts/workflows/cloudflare-carrier-repository-publication-readiness-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-resident-dispatch-live-smoke.ts": "scripts/workflows/cloudflare-carrier-resident-dispatch-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-resident-loop-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-resident-loop-shadow-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-site-action-workflow-live.ts": "scripts/workflows/cloudflare-carrier-site-action-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-site-file-change-proposal-live-smoke.ts": "scripts/workflows/cloudflare-carrier-site-file-change-proposal-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-site-file-materialization-live-smoke.ts": "scripts/workflows/cloudflare-carrier-site-file-materialization-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-site-focus-workflow-live.ts": "scripts/workflows/cloudflare-carrier-site-focus-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-site-next-workflow-live.ts": "scripts/workflows/cloudflare-carrier-site-next-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-claim-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-claim-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-create-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-create-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-finish-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-finish-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-next-workflow-live.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-next-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-report-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-report-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-shadow-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-task-lifecycle-workflow-live.ts": "scripts/workflows/cloudflare-carrier-task-lifecycle-workflow-live.ts",
  "scripts/workflows/cloudflare-carrier-webhook-delay-direct-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-direct-source-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-webhook-delay-directive-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-directive-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-webhook-delay-remote-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-remote-source-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.ts",
  "scripts/workflows/cloudflare-carrier-webhook-delay-shadow-live-smoke.ts": "scripts/workflows/cloudflare-carrier-webhook-delay-shadow-live-smoke.ts",
  "scripts/workflows/cloudflare-site-continuity-bindings.ts": "scripts/workflows/cloudflare-site-continuity-bindings.ts",
  "scripts/workflows/cloudflare-site-continuity-scheduled-task.ts": "scripts/workflows/cloudflare-site-continuity-scheduled-task.ts",
  "scripts/workflows/cloudflare-site-continuity-scheduler.ts": "scripts/workflows/cloudflare-site-continuity-scheduler.ts",
  "scripts/workflows/cloudflare-site-continuity-sync.ts": "scripts/workflows/cloudflare-site-continuity-sync.ts",
  "scripts/shared/carrier-script-surfaces.ts": "scripts/shared/carrier-script-surfaces.ts",
  "scripts/shared/cloudflare-carrier-auth-http.ts": "scripts/shared/cloudflare-carrier-auth-http.ts",
  "scripts/contracts/cloudflare-carrier-authority-transfer-read.test.ts": "scripts/contracts/cloudflare-carrier-authority-transfer-read.test.ts",
  "scripts/contracts/cloudflare-carrier-authority-transfer-readiness-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-authority-transfer-readiness-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-continuation-resume.test.ts": "scripts/contracts/cloudflare-carrier-continuation-resume.test.ts",
  "scripts/contracts/cloudflare-carrier-control-plane-convergence-live.test.ts": "scripts/contracts/cloudflare-carrier-control-plane-convergence-live.test.ts",
  "scripts/contracts/cloudflare-carrier-directive-delivery-review.test.ts": "scripts/contracts/cloudflare-carrier-directive-delivery-review.test.ts",
  "scripts/contracts/cloudflare-carrier-durability-coherence-live.test.ts": "scripts/contracts/cloudflare-carrier-durability-coherence-live.test.ts",
  "scripts/contracts/cloudflare-carrier-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-local-ingress-evidence-read.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-evidence-read.test.ts",
  "scripts/contracts/cloudflare-carrier-local-ingress-evidence.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-evidence.test.ts",
  "scripts/contracts/cloudflare-carrier-local-ingress-provider-liveness-read.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-provider-liveness-read.test.ts",
  "scripts/contracts/cloudflare-carrier-local-ingress-request-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-request-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-local-ingress-request-read.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-request-read.test.ts",
  "scripts/contracts/cloudflare-carrier-local-ingress-request.test.ts": "scripts/contracts/cloudflare-carrier-local-ingress-request.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-draft-reply-proposal-read.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-create-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-outlook-draft-read.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-readback-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-readback-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-send-accepted-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-send-accepted-read.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-send-confirmation-read.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-send-confirmation-read.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-send-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-send-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-status-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-status-shadow-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-mailbox-status-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-mailbox-status-source-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-continuation-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-continuation-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-continuity-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-continuity-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-convergence-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-convergence-live.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-create.test.ts": "scripts/contracts/cloudflare-carrier-operation-create.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-evidence-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-evidence-read.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-focus-review.test.ts": "scripts/contracts/cloudflare-carrier-operation-focus-review.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-focus-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-focus-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-lifecycle-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-lifecycle-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-next-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-next-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-persistence-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-persistence-read.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-recovery-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-recovery-read.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-scope-read.test.ts": "scripts/contracts/cloudflare-carrier-operation-scope-read.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-session-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-operation-session-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-operation-status-put.test.ts": "scripts/contracts/cloudflare-carrier-operation-status-put.test.ts",
  "scripts/contracts/cloudflare-carrier-operator-session-capture.test.ts": "scripts/contracts/cloudflare-carrier-operator-session-capture.test.ts",
  "scripts/contracts/cloudflare-carrier-posture-coherence-live.test.ts": "scripts/contracts/cloudflare-carrier-posture-coherence-live.test.ts",
  "scripts/contracts/cloudflare-carrier-product-read.test.ts": "scripts/contracts/cloudflare-carrier-product-read.test.ts",
  "scripts/contracts/cloudflare-carrier-provider-liveness-refresh-live.test.ts": "scripts/contracts/cloudflare-carrier-provider-liveness-refresh-live.test.ts",
  "scripts/contracts/cloudflare-carrier-provider-liveness-refresh.test.ts": "scripts/contracts/cloudflare-carrier-provider-liveness-refresh.test.ts",
  "scripts/contracts/cloudflare-carrier-provider-liveness-scheduler.test.ts": "scripts/contracts/cloudflare-carrier-provider-liveness-scheduler.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-admission.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-admission.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-execution.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-execution.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-github-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-cloudflare-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-evidence.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-evidence.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-preflight.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-preflight.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-put.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-github-app-secret-put.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-provider-liveness-read.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-provider-liveness-read.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-read.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-read.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-readback-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-readback-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-readiness-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-readiness-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-readiness.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-readiness.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-request-review.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-request-review.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-request.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-request.test.ts",
  "scripts/contracts/cloudflare-carrier-repository-publication-secret-put.test.ts": "scripts/contracts/cloudflare-carrier-repository-publication-secret-put.test.ts",
  "scripts/contracts/cloudflare-carrier-resident-dispatch-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-local-resident-carrier-bridge.test.ts",
  "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence-review.test.ts",
  "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-evidence.test.ts",
  "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-execute.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-execute.test.ts",
  "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-request.test.ts": "scripts/contracts/cloudflare-carrier-resident-dispatch-windows-fallback-request.test.ts",
  "scripts/contracts/cloudflare-carrier-resident-loop-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-resident-loop-shadow-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-script-manifest.test.ts": "scripts/contracts/cloudflare-carrier-script-manifest.test.ts",
  "scripts/contracts/cloudflare-carrier-session-evidence-read.test.ts": "scripts/contracts/cloudflare-carrier-session-evidence-read.test.ts",
  "scripts/contracts/cloudflare-carrier-site-action-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-site-action-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-site-authority-read.test.ts": "scripts/contracts/cloudflare-carrier-site-authority-read.test.ts",
  "scripts/contracts/cloudflare-carrier-site-continuity-loop-report.test.ts": "scripts/contracts/cloudflare-carrier-site-continuity-loop-report.test.ts",
  "scripts/contracts/cloudflare-carrier-site-continuity-publish.test.ts": "scripts/contracts/cloudflare-carrier-site-continuity-publish.test.ts",
  "scripts/contracts/cloudflare-carrier-site-file-change-proposal-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-site-file-change-proposal-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-site-file-change-proposal-review.test.ts": "scripts/contracts/cloudflare-carrier-site-file-change-proposal-review.test.ts",
  "scripts/contracts/cloudflare-carrier-site-file-change-proposal.test.ts": "scripts/contracts/cloudflare-carrier-site-file-change-proposal.test.ts",
  "scripts/contracts/cloudflare-carrier-site-file-materialization-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-site-file-materialization-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-site-file-materialization-read.test.ts": "scripts/contracts/cloudflare-carrier-site-file-materialization-read.test.ts",
  "scripts/contracts/cloudflare-carrier-site-file-materialization.test.ts": "scripts/contracts/cloudflare-carrier-site-file-materialization.test.ts",
  "scripts/contracts/cloudflare-carrier-site-focus-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-site-focus-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-site-membership-put.test.ts": "scripts/contracts/cloudflare-carrier-site-membership-put.test.ts",
  "scripts/contracts/cloudflare-carrier-site-next-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-site-next-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-site-registry-projection.test.ts": "scripts/contracts/cloudflare-carrier-site-registry-projection.test.ts",
  "scripts/contracts/cloudflare-carrier-site-scope-read.test.ts": "scripts/contracts/cloudflare-carrier-site-scope-read.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-assignment-write-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-changed-file-evidence.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-claim-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-claim-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-claim.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-claim.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-create-from-directive-intent.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-create-from-directive-intent.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-create-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-create-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-create.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-create.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-finish-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-finish-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-finish.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-finish.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-next-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-next-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-projection-write-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-read.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-read.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-report-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-report-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-report.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-report.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-role-resolution-write-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-roster-mutation-write-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-shadow-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-source-state-write-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-task-lifecycle-workflow-live.test.ts": "scripts/contracts/cloudflare-carrier-task-lifecycle-workflow-live.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-direct-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-direct-source-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-directive-delivery-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-directive-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-directive-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-observation-primary-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-remote-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-remote-source-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-scheduled-source-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-live-smoke.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-live-smoke.test.ts",
  "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-read.test.ts": "scripts/contracts/cloudflare-carrier-webhook-delay-shadow-read.test.ts",
  "scripts/contracts/cloudflare-intelligence-deploy.test.ts": "scripts/contracts/cloudflare-intelligence-deploy.test.ts",
  "scripts/contracts/cloudflare-site-continuity-bindings.test.ts": "scripts/contracts/cloudflare-site-continuity-bindings.test.ts",
  "scripts/contracts/cloudflare-site-continuity-scheduled-task.test.ts": "scripts/contracts/cloudflare-site-continuity-scheduled-task.test.ts",
  "scripts/contracts/cloudflare-site-continuity-scheduler.test.ts": "scripts/contracts/cloudflare-site-continuity-scheduler.test.ts",
  "scripts/contracts/cloudflare-site-continuity-sync.test.ts": "scripts/contracts/cloudflare-site-continuity-sync.test.ts",
  "scripts/contracts/contract-suite.test.ts": "scripts/contracts/contract-suite.test.ts",
  "scripts/contracts/live-suite.test.ts": "scripts/contracts/live-suite.test.ts",
  "scripts/contracts/suite-loader.ts": "scripts/contracts/suite-loader.ts",
  "scripts/contracts/unit-suite.test.ts": "scripts/contracts/unit-suite.test.ts"
});

export function carrierScriptSurfaceFor(relativePath: any) {
  const normalized = String(relativePath).replaceAll('\\', '/');
  const canonical = CARRIER_SCRIPT_OWNERSHIP[normalized];
  if (!canonical) throw new Error(`cloudflare_carrier_script_unowned:${normalized}`);
  const surface = canonical.split('/')[1];
  if (!CARRIER_SCRIPT_SURFACES[surface === 'read-models' ? 'read_models' : surface]) {
    throw new Error(`cloudflare_carrier_script_surface_unknown:${normalized}`);
  }
  return surface === 'read-models' ? 'read_models' : surface;
}

export function canonicalSurfacePath(surfaceId: any, fileName: any) {
  const surface = CARRIER_SCRIPT_SURFACES[surfaceId];
  if (!surface) throw new Error(`cloudflare_carrier_script_surface_unknown:${surfaceId}`);
  const path = `${surface.directory}/${fileName}`;
  if (!CARRIER_SCRIPT_OWNERSHIP[path]) throw new Error(`cloudflare_carrier_script_unowned:${path}`);
  return path;
}
